// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: proto/productonsale.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductOnSale struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdProductOnSale   int32    `protobuf:"varint,1,opt,name=idProductOnSale,proto3" json:"idProductOnSale,omitempty"`
	Title             int32    `protobuf:"varint,2,opt,name=title,proto3" json:"title,omitempty"`
	Product           *Product `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	Price             string   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	SaleStartDatetime string   `protobuf:"bytes,5,opt,name=saleStartDatetime,proto3" json:"saleStartDatetime,omitempty"`
	SaleEndDatetime   string   `protobuf:"bytes,6,opt,name=saleEndDatetime,proto3" json:"saleEndDatetime,omitempty"`
	Catalog           *Catalog `protobuf:"bytes,7,opt,name=catalog,proto3" json:"catalog,omitempty"`
}

func (x *ProductOnSale) Reset() {
	*x = ProductOnSale{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_productonsale_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductOnSale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductOnSale) ProtoMessage() {}

func (x *ProductOnSale) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productonsale_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductOnSale.ProtoReflect.Descriptor instead.
func (*ProductOnSale) Descriptor() ([]byte, []int) {
	return file_proto_productonsale_proto_rawDescGZIP(), []int{0}
}

func (x *ProductOnSale) GetIdProductOnSale() int32 {
	if x != nil {
		return x.IdProductOnSale
	}
	return 0
}

func (x *ProductOnSale) GetTitle() int32 {
	if x != nil {
		return x.Title
	}
	return 0
}

func (x *ProductOnSale) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *ProductOnSale) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ProductOnSale) GetSaleStartDatetime() string {
	if x != nil {
		return x.SaleStartDatetime
	}
	return ""
}

func (x *ProductOnSale) GetSaleEndDatetime() string {
	if x != nil {
		return x.SaleEndDatetime
	}
	return ""
}

func (x *ProductOnSale) GetCatalog() *Catalog {
	if x != nil {
		return x.Catalog
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdProduct   int32       `protobuf:"varint,1,opt,name=idProduct,proto3" json:"idProduct,omitempty"`
	Name        string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enterprise  *Enterprise `protobuf:"bytes,4,opt,name=enterprise,proto3" json:"enterprise,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_productonsale_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productonsale_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_productonsale_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetIdProduct() int32 {
	if x != nil {
		return x.IdProduct
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetEnterprise() *Enterprise {
	if x != nil {
		return x.Enterprise
	}
	return nil
}

type Enterprise struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdEnterprise int32  `protobuf:"varint,1,opt,name=idEnterprise,proto3" json:"idEnterprise,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Enterprise) Reset() {
	*x = Enterprise{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_productonsale_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Enterprise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enterprise) ProtoMessage() {}

func (x *Enterprise) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productonsale_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enterprise.ProtoReflect.Descriptor instead.
func (*Enterprise) Descriptor() ([]byte, []int) {
	return file_proto_productonsale_proto_rawDescGZIP(), []int{2}
}

func (x *Enterprise) GetIdEnterprise() int32 {
	if x != nil {
		return x.IdEnterprise
	}
	return 0
}

func (x *Enterprise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Catalog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdProductCatalog int32  `protobuf:"varint,1,opt,name=idProductCatalog,proto3" json:"idProductCatalog,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_productonsale_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productonsale_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_proto_productonsale_proto_rawDescGZIP(), []int{3}
}

func (x *Catalog) GetIdProductCatalog() int32 {
	if x != nil {
		return x.IdProductCatalog
	}
	return 0
}

func (x *Catalog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateProductOnSaleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateProductOnSaleResponse) Reset() {
	*x = CreateProductOnSaleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_productonsale_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProductOnSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductOnSaleResponse) ProtoMessage() {}

func (x *CreateProductOnSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productonsale_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductOnSaleResponse.ProtoReflect.Descriptor instead.
func (*CreateProductOnSaleResponse) Descriptor() ([]byte, []int) {
	return file_proto_productonsale_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProductOnSaleResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateProductOnSaleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetProductsOnSaleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetProductsOnSaleRequest) Reset() {
	*x = GetProductsOnSaleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_productonsale_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductsOnSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsOnSaleRequest) ProtoMessage() {}

func (x *GetProductsOnSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productonsale_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsOnSaleRequest.ProtoReflect.Descriptor instead.
func (*GetProductsOnSaleRequest) Descriptor() ([]byte, []int) {
	return file_proto_productonsale_proto_rawDescGZIP(), []int{5}
}

type GetProductsOnSaleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetProductsOnSaleResponse) Reset() {
	*x = GetProductsOnSaleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_productonsale_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductsOnSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsOnSaleResponse) ProtoMessage() {}

func (x *GetProductsOnSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productonsale_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsOnSaleResponse.ProtoReflect.Descriptor instead.
func (*GetProductsOnSaleResponse) Descriptor() ([]byte, []int) {
	return file_proto_productonsale_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductsOnSaleResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetProductsOnSaleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProductOnSaleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductOnSale []*ProductOnSale `protobuf:"bytes,1,rep,name=productOnSale,proto3" json:"productOnSale,omitempty"`
}

func (x *ProductOnSaleList) Reset() {
	*x = ProductOnSaleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_productonsale_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductOnSaleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductOnSaleList) ProtoMessage() {}

func (x *ProductOnSaleList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productonsale_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductOnSaleList.ProtoReflect.Descriptor instead.
func (*ProductOnSaleList) Descriptor() ([]byte, []int) {
	return file_proto_productonsale_proto_rawDescGZIP(), []int{7}
}

func (x *ProductOnSaleList) GetProductOnSale() []*ProductOnSale {
	if x != nil {
		return x.ProductOnSale
	}
	return nil
}

var File_proto_productonsale_proto protoreflect.FileDescriptor

var file_proto_productonsale_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f,
	0x6e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x70, 0x6e, 0x73, 0x61, 0x6c, 0x65, 0x22, 0xa1, 0x02, 0x0a, 0x0d, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x6e, 0x53, 0x61, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x0f,
	0x69, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x6e, 0x53, 0x61, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x4f, 0x6e, 0x53, 0x61, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x30, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x70, 0x6e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x11, 0x73, 0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x61, 0x6c, 0x65, 0x45, 0x6e, 0x64, 0x44, 0x61, 0x74,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x61, 0x6c,
	0x65, 0x45, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x07,
	0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x70, 0x6e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x43, 0x61,
	0x74, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x07, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x22, 0x98,
	0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x64,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69,
	0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x39,
	0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x70, 0x6e, 0x73, 0x61,
	0x6c, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x0a, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x22, 0x44, 0x0a, 0x0a, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x64, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x69,
	0x64, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x49, 0x0a, 0x07, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x64,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43,
	0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4b, 0x0a, 0x1b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x6e, 0x53, 0x61, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x4f, 0x6e, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x73, 0x4f, 0x6e, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x57,
	0x0a, 0x11, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x6e, 0x53, 0x61, 0x6c, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x42, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x6e,
	0x53, 0x61, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x70, 0x6e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x4f, 0x6e, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x4f, 0x6e, 0x53, 0x61, 0x6c, 0x65, 0x32, 0xdd, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x6e, 0x53, 0x61, 0x6c,
	0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x70, 0x6e, 0x73, 0x61, 0x6c,
	0x65, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x6e, 0x53, 0x61, 0x6c, 0x65, 0x1a,
	0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x70, 0x6e, 0x73, 0x61, 0x6c, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x6e, 0x53,
	0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x4f, 0x6e, 0x53, 0x61,
	0x6c, 0x65, 0x12, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x70, 0x6e, 0x73, 0x61,
	0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x4f, 0x6e,
	0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x70, 0x6e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x4f, 0x6e, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x73, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2d, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_productonsale_proto_rawDescOnce sync.Once
	file_proto_productonsale_proto_rawDescData = file_proto_productonsale_proto_rawDesc
)

func file_proto_productonsale_proto_rawDescGZIP() []byte {
	file_proto_productonsale_proto_rawDescOnce.Do(func() {
		file_proto_productonsale_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_productonsale_proto_rawDescData)
	})
	return file_proto_productonsale_proto_rawDescData
}

var file_proto_productonsale_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_productonsale_proto_goTypes = []interface{}{
	(*ProductOnSale)(nil),               // 0: productpnsale.ProductOnSale
	(*Product)(nil),                     // 1: productpnsale.Product
	(*Enterprise)(nil),                  // 2: productpnsale.Enterprise
	(*Catalog)(nil),                     // 3: productpnsale.Catalog
	(*CreateProductOnSaleResponse)(nil), // 4: productpnsale.CreateProductOnSaleResponse
	(*GetProductsOnSaleRequest)(nil),    // 5: productpnsale.GetProductsOnSaleRequest
	(*GetProductsOnSaleResponse)(nil),   // 6: productpnsale.GetProductsOnSaleResponse
	(*ProductOnSaleList)(nil),           // 7: productpnsale.ProductOnSaleList
}
var file_proto_productonsale_proto_depIdxs = []int32{
	1, // 0: productpnsale.ProductOnSale.product:type_name -> productpnsale.Product
	3, // 1: productpnsale.ProductOnSale.catalog:type_name -> productpnsale.Catalog
	2, // 2: productpnsale.Product.enterprise:type_name -> productpnsale.Enterprise
	0, // 3: productpnsale.ProductOnSaleList.productOnSale:type_name -> productpnsale.ProductOnSale
	0, // 4: productpnsale.ProductService.CreateProductOnSale:input_type -> productpnsale.ProductOnSale
	5, // 5: productpnsale.ProductService.GetProductsOnSale:input_type -> productpnsale.GetProductsOnSaleRequest
	4, // 6: productpnsale.ProductService.CreateProductOnSale:output_type -> productpnsale.CreateProductOnSaleResponse
	6, // 7: productpnsale.ProductService.GetProductsOnSale:output_type -> productpnsale.GetProductsOnSaleResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_productonsale_proto_init() }
func file_proto_productonsale_proto_init() {
	if File_proto_productonsale_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_productonsale_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductOnSale); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_productonsale_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_productonsale_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Enterprise); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_productonsale_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Catalog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_productonsale_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProductOnSaleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_productonsale_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductsOnSaleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_productonsale_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductsOnSaleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_productonsale_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductOnSaleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_productonsale_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_productonsale_proto_goTypes,
		DependencyIndexes: file_proto_productonsale_proto_depIdxs,
		MessageInfos:      file_proto_productonsale_proto_msgTypes,
	}.Build()
	File_proto_productonsale_proto = out.File
	file_proto_productonsale_proto_rawDesc = nil
	file_proto_productonsale_proto_goTypes = nil
	file_proto_productonsale_proto_depIdxs = nil
}
